default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Quiz_App_development

test:
  <<: *default
  database: Quiz_App_test

production:
  <<: *default
  database: Quiz_App_production
  username: Quiz_App
  password: <%= ENV["QUIZ_APP_DATABASE_PASSWORD"] %>
